# Generated by Django 4.2.4 on 2023-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, verbose_name='Номер счетчика')),
                ('amps', models.CharField(blank=True, null=True, verbose_name='Текущий ток (кол-во Ампер)')),
                ('kilowatt', models.CharField(blank=True, null=True, verbose_name='Потребление энергии')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
            ],
            options={
                'verbose_name': 'показание',
                'verbose_name_plural': 'показания',
            },
        ),
        migrations.CreateModel(
            name='EnergyMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True, verbose_name='Номер счетчика')),
            ],
            options={
                'verbose_name': 'счетчик',
                'verbose_name_plural': 'счетчики',
            },
        ),
    ]
