# Generated by Django 4.2.4 on 2023-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymeasurements',
            name='amps',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущий ток (кол-во Ампер)'),
        ),
        migrations.AlterField(
            model_name='energymeasurements',
            name='kilowatt',
            field=models.FloatField(blank=True, null=True, verbose_name='Потребление энергии'),
        ),
        migrations.AlterField(
            model_name='energymeasurements',
            name='number',
            field=models.IntegerField(max_length=24, verbose_name='Номер счетчика'),
        ),
        migrations.AlterField(
            model_name='energymeter',
            name='number',
            field=models.IntegerField(max_length=24, unique=True, verbose_name='Номер счетчика'),
        ),
    ]
